name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: ${{ matrix.arch }}-pc-windows-msvc
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [i686, x86_64]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        shell: bash
        run: |
          clang-cl --target=${{ matrix.arch }}-pc-windows-msvc -Brepro -LD \
                   -O2 -Zl -fuse-ld=lld -v api-ms-win-core-path-l1-1-0.c \
                   -link -def:api-ms-win-core-path-l1-1-0.def -noimplib \
                   shlwapi.lib
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}-pc-windows-msvc
          path: api-ms-win-core-path-l1-1-0.dll
